version: '2'
services:
  cassandra-node1:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=password123
    volumes:
      - /Users/delta/Documents/datastores/dockerdata/cassandra-node1:/bitnami
    ports:
      - "9042:9042"
    networks:
      - cassandra-network

  cassandra-node2:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD=password123
    volumes:
      - /Users/delta/Documents/datastores/dockerdata/cassandra-node2:/bitnami
    networks:
      - cassandra-network

  cassandra-node3:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD=password123
    volumes:
      - /Users/delta/Documents/datastores/dockerdata/cassandra-node3:/bitnami
    networks:
      - cassandra-network

  cassandra-node4:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD=password123
    volumes:
      - /Users/delta/Documents/datastores/dockerdata/cassandra-node4:/bitnami
    networks:
      - cassandra-network

  cassandra-node5:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD=password123
    volumes:
      - /Users/delta/Documents/datastores/dockerdata/cassandra-node5:/bitnami
    networks:
      - cassandra-network
networks:
  cassandra-network:
    driver: default