# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
networks:
  es-kibana-tier:
    driver: bridge

version: "2"
services:
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:8
    volumes:
      - "/Users/delta/Documents/datastores/dockerdata/elastic-kibana/es:/bitnami/elasticsearch"
    networks:
      - es-kibana-tier  
    ports:
      - '9200:9200'
      - '9300:9300'      
  kibana:
    image: docker.io/bitnami/kibana:8
    ports:
      - "5601:5601"
    volumes:
      - "/Users/delta/Documents/datastores/dockerdata/elastic-kibana/kibana:/bitnami/kibana"
    depends_on:
      - elasticsearch
    networks:
      - es-kibana-tier