# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
networks:
  app-tier:
    driver: bridge

services:
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:8
    networks:
      - app-tier
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - '/Users/delta/Documents/datastores/dockerdata/elasticsearch:/bitnami/elasticsearch/data'
