version: '2'
services:
  cassandra:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
    volumes:
      - /Users/delta/Documents/datastores/dockerdata/cassandra:/bitnami
    ports:
      - 7000:7000
      - 9042:9042