version: '3.8'
services:
  cache:
    image: redis:6.2.13-alpine3.18
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes: 
      - /Users/delta/Documents/datastores/dockerdata/redis:/data